# Generated by Django 3.1 on 2020-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiturient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=255)),
                ('field_of_study', models.CharField(default='', max_length=255)),
                ('is_accepted', models.BooleanField(default=False)),
                ('res_sum', models.IntegerField(default=0)),
                ('min_ball', models.IntegerField(default=0)),
                ('cnt_of_places', models.IntegerField(default=0)),
                ('cur_place', models.IntegerField(default=0)),
            ],
        ),
    ]
